### ISSUE TITLE
Support Thunderstorm and Next-Week Properties in Portuguese

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-io-translations#109]
In the near future, the API will begin generating the following new properties:

*   `possible-thunderstorm`
*   `thunderstorm`
*   `next-sunday`
*   `next-monday`
*   `next-tuesday`
*   `next-wednesday`
*   `next-thursday`
*   `next-friday`
*   `next-saturday`

Add support for these properties to Portuguese. (Information is available in the README, and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

**Comment by ironwallaby** [comment]
Tagging @pedronoliveira. Please take a look if you get a chance!

**Comment by pedronoliveira** [comment]
Will do as soon as I get a chance!
