### ISSUE TITLE
Properly translate possible-* cases in German

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-io-translations#147]
I noticed this morning that the [German translation](https://github.com/darkskyapp/forecast-io-translations/blob/master/lib/lang/de.js) was missing the following terms:

*   `possible-very-light-precipitation`
*   `possible-light-precipitation`
*   `possible-very-light-rain`
*   `possible-light-rain`
*   `possible-very-light-sleet`
*   `possible-light-sleet`
*   `possible-very-light-snow`
*   `possible-light-snow`

I added a quick hack to correct for this, simply copying the terminology from the related cases (e.g. `very-light-precipitation`, `light-precipitation`, etc.). Could somebody who is familiar with German fix these lines such that they indicate that the precipitation only has a chance of occurring?

```
  "possible-very-light-precipitation": "leichter Niederschlag", // FIXME
  "possible-light-precipitation": "leichter Niederschlag", // FIXME
  "possible-very-light-rain": "Nieselregen", // FIXME
  "possible-light-rain": "leichter Regen", // FIXME
  "possible-very-light-sleet": "leichter Graupelregen", // FIXME
  "possible-light-sleet": "leichter Graupelregen", // FIXME
  "possible-very-light-snow": "leichter Schneefall", // FIXME
  "possible-light-snow": "leichter Schneefall", // FIXME
```

Based on the `possible-thunderstorm` term, my guess is that the translation would be the following, but I would appreciate confirmation/correction:

```
  "possible-very-light-precipitation": "mögliche leichter Niederschlag",
  "possible-light-precipitation": "mögliche leichter Niederschlag",
  "possible-very-light-rain": "mögliche Nieselregen",
  "possible-light-rain": "mögliche leichter Regen",
  "possible-very-light-sleet": "mögliche leichter Graupelregen",
  "possible-light-sleet": "mögliche leichter Graupelregen",
  "possible-very-light-snow": "mögliche leichter Schneefall",
  "possible-light-snow": "mögliche leichter Schneefall",
```

Thanks!

(Tagging @jacbz @mrkcohen @TheMikeGraz as they previously contributed to this translation.)

**Comment by jacbz** [comment]
In German, you would simply add "möglich" (possible) at the end of the sentence. So for example, "**Possible** light precipitation [on Friday]" becomes "Leichter Regen [am Freitag] **möglich**".

Also:
- very light precipitation has a German term: "Nieselregen"
- possible-thunderstorm is incorrect, it should be "Gewitter.... möglich" as above

**Comment by ironwallaby** [comment]
Does "Nieselregen" refer to all kinds of precipitation, or does it refer specifically to rain (e.g. liquid precipitation)?

**Comment by jacbz** [comment]
Nieselregen is defined as light rain where the rain drops are smaller than 0.5 millimetres in diameter.

**Comment by ironwallaby** [comment]
Got it, thanks. So we'll want to use that for `very-light-rain`, but _not_ `very-light-precipitation`, which might not be liquid. (We use `-precipitation` when we don't know the type.)

**Comment by ironwallaby** [comment]
Merged a fix in. Thanks all!
