### ISSUE TITLE
Errors in German Translation

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-io-translations#31]
A user writes, there is an error in the German translation. The english summary "Drizzle starting in the evening." is translated to  "In Abend Nieselregen" where it should be "Am Abend Nieselregen."

I would love to see this fixed, but I don't speak German. Could somebody who does make the appropriate changes?

**Comment by ironwallaby** [comment]
Another sentence that is reported as being problematic: "schwer bewölkt" should instead be "stark bewölkt".

**Comment by jacbz** [comment]
I've tried fixing these [here](https://github.com/darkskyapp/forecast-io-translations/pull/45).

**Comment by ironwallaby** [comment]
(This ticket was fixed some time ago with commit 46260bbb6859903a9ff89af3c1ee79a6828d5f59.)
