### ISSUE TITLE
Errors in Dutch Translation

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-io-translations#32]
We received the following comments from a developer using the API:

> The following two sentences have minor grammatical problems:
> 
> 1.  Lichte regen vandaag tot op zondag met temperaturen stijgend tot 19°C op zondag
> 2.  Lichte regen morgen tot van maandag met temperaturen stijgend tot 16°C op maandag.
> 
> Literally translated is:
> 
> 1.  Light rain today till up Sunday with temperatures increasing to 19°C on Sunday.
> 2.  Light rain tomorrow till from Monday with temperatures increasing to 16°C on Monday.
> 
> A better sentence would be:
> 
> 1.  Lichte regen vandaag t/m zondag met temperaturen stijgend tot 19°C op zondag
> 2.  Lichte regen morgen tot maandag met temperaturen stijgend tot 16°C op maandag.

I believe the existing translation is from @basvdijk and @realjax... any thoughts on this?

**Comment by realjax** [comment]
He is right.  But I think the way the software constructs these sentences prohibits it.

Cheers

"J. T. L." <notifications@github.com> schreef op 28 april 2015 20:02:36 CEST:

**Comment by basvdijk** [comment]
I agree with the proposed translation to be a better one.

**Comment by ironwallaby** [comment]
Thanks.

@realjax - Could you be more specific? Perhaps I can work out a way around the issue.

**Comment by realjax** [comment]
Again, I'm not sure,  but take for instance this part
..tot van maandag..  

The 'van maandag' part is also used in the a sentence like:

'From monday until sunday' (Van maandag tot zondag) . If we leave out the word 'van' as the  developer rightfully suggested,  his example would be correct but this one would be incorrect as it no longer has a translation for the word 'from'

It's a consequence of the fact that sentences in English are not constructed the same way as Dutch ones are. I tried to level those problems out as much as possible for the original Dutch translation but couldn't completely prevent the awkward sentence every now and then.

**Comment by ironwallaby** [comment]
Well, what I mean is, what is it in the module that prevents fixing this? There is a mechanism which can be used to inspect the context in which a phrase is used so as to be able to determine how to structure that phrase. Would this be sufficient to work around the issue in this case?

(Example: https://github.com/darkskyapp/forecast-io-translations/blob/master/lib/lang/de.js#L100-L109 )

**Comment by realjax** [comment]
Could be, I'll look into the code when I have time to see if this would work!
