### ISSUE TITLE
Errors in Russian and Ukrainian translations

### ISSUE THREAD

**Issue by egormetlitsky** [darkskyapp/forecast-io-translations#73]
The two translations have a function time2, which changes "tomorrow-afternoon" ("завтра днем" [ru], "завтра вдень" [uk]) to "tomorrow-morning" ("завтрашнего утра" [ru], "завтрашнього ранку" [uk]). Here should "завтрашнего дня" [ru], "завтрашнього дня" [uk] be.

**Comment by ironwallaby** [comment]
Thanks for pointing this out. I would be very appreciative of a patch, if you don't mind submitting one—Cyrillic is completely foreign to my eyes, and I would likely make a mistake in doing so myself!

**Comment by egormetlitsky** [comment]
done

**Comment by ironwallaby** [comment]
This has been merged in. Thanks so much!
