### ISSUE TITLE
Support Thunderstorm and Next-Week Properties in Belarusian

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-io-translations#90]
In the near future, the API will begin generating the following new properties:

*   `possible-thunderstorm`
*   `thunderstorm`
*   `next-sunday`
*   `next-monday`
*   `next-tuesday`
*   `next-wednesday`
*   `next-thursday`
*   `next-friday`
*   `next-saturday`

Add support for these properties to Belarusian. (Information is available in the README, and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

**Comment by ironwallaby** [comment]
Tagging @egormetlitsky. Please take a look if you have a chance!

**Comment by egormetlitsky** [comment]
Done with #110
