### ISSUE TITLE
Support Thunderstorm and Next-Week Properties in Catalan

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-io-translations#93]
In the near future, the API will begin generating the following new properties:

*   `possible-thunderstorm`
*   `thunderstorm`
*   `next-sunday`
*   `next-monday`
*   `next-tuesday`
*   `next-wednesday`
*   `next-thursday`
*   `next-friday`
*   `next-saturday`

Add support for these properties to Catalan. (Information is available in the README, and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

**Comment by ironwallaby** [comment]
Tagging @eriscoand and @mrkcohen. Please take a look if you get the chance!

**Comment by eriscoand** [comment]
Ok
