### ISSUE TITLE
Support Thunderstorm and Next-Week Properties in Estonian

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-io-translations#98]
In the near future, the API will begin generating the following new properties:

*   `possible-thunderstorm`
*   `thunderstorm`
*   `next-sunday`
*   `next-monday`
*   `next-tuesday`
*   `next-wednesday`
*   `next-thursday`
*   `next-friday`
*   `next-saturday`

Add support for these properties to Estonian. (Information is available in the README, and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

**Comment by ironwallaby** [comment]
Tagging @oskarkala. Please take a look if you get a chance!

**Comment by oskarkala** [comment]
Hey, will do it ASAP. Quick question though: could you give me an example sentence with "next-sunday", as I am wondering what the context is (on the next sunday, next sunday, etc). Estonian is a very case-sensitive language.. :)

**Comment by ironwallaby** [comment]
Sure. The case in English is: suppose it is currently Friday (10 Mar), and the high temperature for the next week is a week from today (e.g. next Friday, 17 Mar). We might return a summary, saying, "No precipitation for the week, with temperatures rising to 68° on Friday." To an English speaker, this is confusing, since _today_ is Friday—so they wouldn't be sure if the "Friday" is today or a week from today.

We are trying to update the API to instead say "No precipitation for the week, with temperatures rising to 68° next Friday." This is no longer ambiguous to an English speaker.

Another example of context is in the English language tests:

```json
{
  "Light snow on Tuesday and next Wednesday, with temperatures falling to 0\u00B0C on Sunday.":
    ["sentence", ["with",
      ["during", "light-snow", ["and", "tuesday", "next-wednesday"]],
      ["temperatures-falling",
        ["celsius", 0],
        "sunday"]]],
}
```

This example assumes that today is Wednesday, and that snow would occur both six days from today and seven days from today.

Does that help make it clearer?

**Comment by oskarkala** [comment]
Hey,
Yes, this is made it very clear :) Working on it and will be pushing in a bit.

Best wishes,
Oskar J. Kala

**Comment by oskarkala** [comment]
Hi, would there be a case where 'next-wednesday' is in a sentence with 'until'? 
E.g. 
"Windy until next Wednesday.":
    ["sentence", ["until", "medium-wind", "next-wednesday"]]

**Comment by ironwallaby** [comment]
Presently, no---`next-wednesday` can only appear in these cases:

```
["during", X, "next-wednesday"]
["during", X, ["and", Y, "next-wednesday"]]
["temperatures-rising", X, "next-wednesday"]
["temperatures-falling", X, "next-wednesday"]
```

**Comment by oskarkala** [comment]
It is okay anyway, found a way to work around every possible scenario. Sent a pull request.

Best wishes
